---
title: "Untitled"
author: "ShuYu"
date: "2019年5月22日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
invoiceList <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/invoiceList.csv",
col_types = cols(訂單時間.以訂單時區顯示. = col_character()))
names(invoiceList)[[2]] <- "訂單時區之下單時間"
```

#midterm 6.2
```{r}
library(lubridate)
tplogic <- invoiceList$訂單時區=="Asia/Taipei"
nylogic <- invoiceList$訂單時區=="America/New_York"
tptime <- ymd_hms(invoiceList$訂單時區之下單時間[tplogic], tz="Asia/Taipei" )
invoiceList$UTC時間[tplogic] <- with_tz(tptime, tzone ="UTC")
nytime <- ymd_hms(invoiceList$訂單時區之下單時間[nylogic], tz="America/New_York" )
invoiceList$UTC時間[nylogic] <- with_tz(nytime, tzone ="UTC")
invoiceList
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
}
```
```{r}
gpa_fun("479W9ee8e")
gpa_fun("9efW9aea5")
```


#請把以America/New_York時區輸入的時間字串"1973-02-21 12:05:22"，轉成date time class, 再改成Asia/Taipei時間顯示
```{r}
nytime2 <- ymd_hms("1973-02-21 12:05:22", tz="America/New_York")
nytime3 <- with_tz(nytime2, tzone = "Asia/Taipei")
nytime3
```

#用function表達
```{r}
ymd_hms_tzChange <- function(input, fromTzone, toTzone){
  time1 <- ymd_hms(input, tz=fromTzone )
  finaltime <- with_tz(time1, tzone = toTzone )
  return(finaltime)
}

ymd_hms_tzChange("2019-05-22 16:05:30", "Asia/Taipei", "America/New_York")
ymd_hms_tzChange(invoiceList$`訂單時區之下單時間`[tplogic], "Asia/Taipei", "UTC")
```


```{r}
library(stringr)
sample(99:103,15,replace = T)-> yy
sample(1:12,15,replace=T)-> mm
str_c("民國",str_pad(yy,3,"left","0"),"年",mm,"月") -> twDates
twDates
```

#把民國年月轉成需元年月的寫法
```{r}
#查string_r cheatsheet p.2 

library(stringr); library(lubridate)
#regular expression 民國可以換成任何字眼(前面都是__)
# +號：__們
#幫我把twDate"民國"後面的數字們
yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911 
#幫我取出taDate"月"之前的數字們
mm<-str_extract(twDates,"[:digit:]+(?=月)")
#組合在一起後變成datetime
yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))
```

#請寫一個函數其名稱為date_convert_twYM，且date_convert_twYM(x)可以把一個民國年月字串物件x轉成date time class的西元年月日物件輸出
```{r}
date_convert_twYM <- function(twdate){
  yyyy<-as.integer(str_extract(twdate,"(?<=(民國))[:digit:]+"))+1911 
  mm<-str_extract(twdate,"[:digit:]+(?=月)")
  yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-")) 
  
  return(yyyymmdd)
}

date_convert_twYM("民國108年5月")
date_convert_twYM(twDates)
```

```{r}
utility_cobb_douglass2 <- function(x,y,.alpha=0.5,.beta=0.5){
  utilValue <- x^.alpha*y^.beta
  return(utilValue)
}
```

```{r}
utility_cobb_douglass2(1,2) # 使用預設值
utility_cobb_douglass2(1,2,0.5,0.8) # 自定參數值
```

#使用預設值
```{r}
date_convert_twYM <- function(twdate, day="01"){              #日期有預設值，類別為character，如果只寫01，input就是numeric
  yyyy<-as.integer(str_extract(twdate,"(?<=(民國))[:digit:]+"))+1911 
  mm<-str_extract(twdate,"[:digit:]+(?=月)")
  yyyymmdd <- ymd(str_c(yyyy,mm,day,sep="-"))
  
  return(yyyymmdd)
}

date_convert_twYM("民國108年5月")
date_convert_twYM(twDates, "04")
```






















