---
title: "Untitled"
author: "ShuYu"
date: "2019年5月15日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
Vector1 <- letters[1:6]
Vector1

names(Vector1)
```

```{r}
names(Vector1) <- c('名稱1','名稱2','名稱3','名稱4','名稱5','名稱6')
names(Vector1)
```

```{r}
names(Mat1) <- letters[1:6]
names(Mat1)
```

```{r}
matObj1
```

```{r}
colnames(matObj1) 
rownames(matObj1)
```
```{r}
colnames(matObj1) <-c('欄位1','欄位2','欄位3','欄位4')
colnames(matObj1)
matObj1
```
```{r}
rownames(matObj1) <- c('行：1','行：2','行：3','行：4','行：5')
matObj1
```
```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在
a[[5]] <- "7" # 元素不存在，判定為新創立一個元素
a
```
```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)

b[[3]] <- FALSE
b$"元素5" <- "hi"

b
```
```{r}
library(readr)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))
```

```{r}
library(lubridate)
exData3[[1]] <- ymd(exData3[[1]])
isAsiaCrisis <- exData3[[1]] >= ymd("1997-06-01") & exData3[[1]] <= ymd("1998-12-01")
isAsiaCrisis
exData3 <- exData3[isAsiaCrisis,]
```



























