---
title: "Untitled"
author: "ShuYu"
date: "2019年6月5日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
utility_cobb_douglass <- function(x,y,.alpha,.beta){
  utilValue <- x^.alpha*y^.beta # 程序產生output值
  return(utilValue) # 傳回output值
}
```

```{r}
#不指定input名稱:照順序
utility_cobb_douglass(1,2,0.5,0.8)
#指定名稱
utility_cobb_douglass(1,2,.beta=0.8,.alpha=0.5)
```
```{r}
utility_cobb_douglass(y=2,x=1,0.5,0.8)
```

#iteration
```{r}
load(url("https://github.com/tpemartin/github-data/blob/master/loopTranscriptData.Rda?raw=true"))
```

```{r}
gpa_fun(transcriptDataFinal$學號[[1]])
```

```{r}
studentIds <- unique(transcriptDataFinal$學號)
studentIds5 <- studentIds[1:5]
studentIds5
```

```{r}
for(i in studentIds5){
  print(i) # 印出studentIds5[[i]]
}
```
#法1
```{r}
for(i in studentIds5){
  gpa_fun(i)
  print(gpa_fun(i))
}
```
#法2
```{r}
for(i in c(1:5)){
  print(i)
  print(studentIds5[[i]])
}
```
#法3
```{r}
seq_along(studentIds5) #有幾個元素(比較:(1:5)，避免數錯)
for(i in seq_along(studentIds5)){
  print(studentIds5[[i]])
}
```

#examplle2
```{r}
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)
```

#法1
```{r}
library(stringr)
for(i in studentIds5){
  if("@gmail.com" %in% i){
    str_c(i,"@gmail.com")
  }
}
```

```{r}
for(i in gmailAddress){
  print(i)
}
```

```{r}
for(i in c(1:4)){
  print(i)
  print(gmailAddress[[i]])
}
```

```{r}
for(i in seq_along(gmailAddress)){
  print(i)
  print(gmailAddress[[i]])
}
```





















