---
title: '2019-03-27'
author: "ShuYu"
date: "2019年3月27日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
LisbonDateTime <- with_tz(twDateTime,tz="Europe/Lisbon")
```


```{r}
typeof(LisbonDateTime)
as.integer(LisbonDateTime)
as.integer(twDateTime)
```
```{r}
twDateTime <- ymd_hms("2019-03-19 13:00:00", tz="Asia/Taipei")
LisbonDateTime <- with_tz(twDateTime,tz="Europe/Lisbon")
```

```{r}
typeof(LisbonDateTime)
as.integer(LisbonDateTime)
as.integer(twDateTime)
```

```{r}
twDT <- ymd_hms("2019-03-14 08:18:47",tz="Asia/Taipei")
nowtime <- mdy("March,3 2019",tz="Asia/Taipei")
nowtime2 <- ymd("2018-09-11",tz="Asia/Taipei")
```

```{r}
typeof(nowtime)
as.double(nowtime)
```

```{r}
ymd("2012-03-19")
as.integer(ymd("2017-09-08")) 
as.integer(ymd("2019-03-19")) 
```
```{r}
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
aL+bL
```

```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
a+bL
a*bL
class(aL*b)
class(aL/b)
```
```{r}
as.integer(a)
typeof(a)
typeof(aL)
levels(aL)
sum(aL)
```

```{r}
a+4
a^2
typeof(a)
typeof(b)
```
```{r}
twDateTime+3600
typeof(twDateTime)
```
```{r}
DateTime1 <- ymd("2012-03-19")
DateTime2 <- ymd("2019-03-27")
DateTime2-DateTime1
as.double(DateTime2-DateTime1)
as.integer(DateTime2 - DateTime1)
DateTime1 + years(7)
DateTime1 + 365
DateTime1 + dyears(7)
```

```{r}
x <- 5
y <- 7
x2 <- c(1,5,10)
y2 <- c(-1,5,20)
x != y
x >= y2
z = x
z == x
x2 < y2
y2+x
```
```{r}
x3 <- c("小明","小花")
y3 <- c("小明","小華")
x3 != y3
x3 == y3
```

```{r}
x4 <- c(1,5,8)
y4 <- c(5,8)


x4 %in% y4
y4 %in% x4
x2
y4
y4 %in% x2
```

```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華")

x2 == y2

```

```{r}
is.na(x2)
sum(x2, na.rm = TRUE)
```

