---
title: '2019-04-10'
author: "ShuYu"
date: "2019年4月10日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(stringr)
```
#str_subset:有的就挑出來
#str_detect:有沒有符合跟我說
```{r}
course <- c("個體經濟學","投資學","總體經濟學")
str_subset(course,"經濟學")
str_detect(course,"經濟學")
```

#str_sub:取出特定元素
```{r}
studentID<-c(
  '410177115','410176080','410174233','410177011','410182045','410176014')
str_sub(studentID,5,6) #取出學系號
str_sub(studentID,start = 2, end = 4) #取出學年
str_sub(studentID, 8,9)
```

#str_c:合併字串向量(contenate)
```{r}
month <- c("3","4","2")
day <- c("11","5","7")
char1 <- c("月","月","月")
char2 <- c("日","日","日")
month
char1
day 
char2
str_c(month,char1,day,char2)
```

#比較懶的str_c
```{r}
str_c(month,c("月"),day,c("日"))
str_c(month,"月",day,"日")
```

```{r}
month
day
str_c(month,day,sep="-") #sepration(把他們分隔)
```

#str_split:切開來
```{r}
dates <- c("3-11", "4-5",  "2-7")
str_split(dates,"-")
```

#str_replace:取代(第一個)
```{r}
dates
str_replace(dates,"-","月")
```

#str_replace_all:全部取代
```{r}
dates2 <- c("3-11-2019", "4-5-2017",  "2-7-2015")
dates2
str_replace(dates2,"-","/")
str_replace_all(dates2,"-","/")
```

```{r}
library(readr)
library(readr)
githubData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/githubData.csv")
username <- githubData$`GitHub username`[11:16]
reponame <- githubData$`GitHub repo name`[11:16]

str_c("https://raw.githubusercontent.com/","username/","reponame")
str_c("https://github.com",username,reponame,sep="/")
```
```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/%E7%AC%AC%E4%B8%89%E5%B1%86%E7%B6%93%E6%BF%9F%E6%92%AD%E5%AE%A2%E7%AB%B6%E8%B3%BD%E5%8F%83%E8%B3%BD%E4%BD%9C%E5%93%81%E6%8A%95%E7%A5%A8%E7%B5%90%E6%9E%9C%E6%A8%A3%E6%9C%AC%20-%20Sheet1.csv")
birthday<-filmVotingData$`出生西元年月日（驗證本人用）`

head(birthday)
x1 <- str_sub(birthday,1,4)
x2 <- str_sub(birthday,5,6)
x3 <- str_sub(birthday,7,8)
head(str_c("西元",x1,"年",x2,"月",x3,"日"))
```
```{r}
library(lubridate)
roc_year <-c("099/01","099/02","099/03")
roc_year1 <- str_sub(roc_year,2,3)
mon <- str_sub(roc_year,5,6)

cen_year <- as.integer(roc_year1)+1911
cen_year
cen_year <- as.character(cen_year)
mon<-as.character(mon)

str_c(cen_year,"年",mon,"月")
```





