---
title: "Untitled"
author: "ShuYu"
date: "2019年4月17日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
aWithNames <- c(
  a1=1,
  a2=2,
  a3=3
)
typeof(a)
aWithNames
```


```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1,3,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
```

```{r}
plasticContainer

plasticContainer[["greenBox"]] 
plasticContainer[[1]]

```

```{r}
plasticContainer[["greenBox"]][[2]]

x <- plasticContainer[["greenBox"]] 
x[[1]]
```


```{r}
成績單 <- c(
  個經=90,
  總經=77,
  統計=88
)

成績單[[1]]
```

```{r}
studentRecord <-
  list(
    學號="410073058",
    姓名="王小明",
    性別="男",
    學年平均成績=list(
      一年級=88,
      二年級=90.3,
      三年級=92,
      四年級=95
    )
  )

studentRecord[[2]]
studentRecord[[4]][[3]]
class(studentRecord[[4]][[3]])

```

```{r}
plasticContainer
plasticContainer[c("greenBox","redBox")] 
class(plasticContainer[c(1,2)])
```

```{r}
extract1 <- plasticContainer[c("greenBox")]   #塑膠箱子還在
extract1[[1]]                                 #拿出了綠色箱子
extract1[[1]][[1]]                            #先把綠箱子拿出來，再把第一個東西拿出來
extract2 <- plasticContainer[[c("greenBox")]] #拿出綠色箱子
extract2[[1]]                                 #從綠色箱子拿出第一個東西
class(extract1)
class(extract2)
```





